### ISSUE TITLE
Work with VFS300

### ISSUE THREAD

**Issue by Lopan** [andree182/vfs301#1]
Work very fine with VSF300 (Bus 001 Device 004: ID 138a:0008 Validity Sensors, Inc. VFS300 Fingeprint Reader)!

just change the proto.c line (135)
from:
        dev->devh = libusb_open_device_with_vid_pid(NULL, 0x138a, 0x0005);
to:
        dev->devh = libusb_open_device_with_vid_pid(NULL, 0x138a, 0x0008);

Congratulations!

(Dell Vostro 3500)

**Comment by andree182** [comment]
Great to hear about that - I'll add this to the description then, and extend the code.
