### ISSUE TITLE
Integrate to libfprint

### ISSUE THREAD

**Issue by Lopan** [andree182/vfs301#2]
Dear andree182,

You think about porting this driver to libfprint?

Congratulations for the wonderful job!

best regards,

**Comment by andree182** [comment]
Hi there,

sure - I just more or less finished cleaning up, so the next step is studying libfprint and integrating the driver... :)

The only issue I see now is that the fingerprints coming from the device are kind of distorted - depending on the (varying) speed of the finger. Maybe there's some hint in the data to transform it into canonical form, or we'll have to use some heuristics - we'll see about that in the next days...

**Comment by andree182** [comment]
Done now... :-)
