### ISSUE TITLE
Not possible to compile it

### ISSUE THREAD

**Issue by vedovatti** [andree182/vfs301#4]
Hi Andree. Thanks for working on this driver. I cannot compile it. (just for the record I am not a programmer). So when I compile it i get:
gcc -ggdb `pkg-config --cflags libusb-1.0` `pkg-config --libs libusb-1.0` -o cli proto.c cli.c
/tmp/cchqESW9.o: In function `usb_init':
/home/carlos/Desktop/VFS301/cli/cli.c:52: undefined reference to`libusb_init'
/home/carlos/Desktop/VFS301/cli/cli.c:60: undefined reference to `libusb_open_device_with_vid_pid'
/home/carlos/Desktop/VFS301/cli/cli.c:73: undefined reference to`libusb_kernel_driver_active'
/home/carlos/Desktop/VFS301/cli/cli.c:75: undefined reference to `libusb_detach_kernel_driver'
/home/carlos/Desktop/VFS301/cli/cli.c:81: undefined reference to`libusb_claim_interface'
/home/carlos/Desktop/VFS301/cli/cli.c:88: undefined reference to `libusb_reset_device'
/home/carlos/Desktop/VFS301/cli/cli.c:94: undefined reference to`libusb_control_transfer'
/tmp/cchqESW9.o: In function `usb_deinit':
/home/carlos/Desktop/VFS301/cli/cli.c:110: undefined reference to`libusb_reset_device'
/home/carlos/Desktop/VFS301/cli/cli.c:117: undefined reference to `libusb_release_interface'
/home/carlos/Desktop/VFS301/cli/cli.c:124: undefined reference to`libusb_close'
/home/carlos/Desktop/VFS301/cli/cli.c:130: undefined reference to `libusb_exit'
/tmp/cchqESW9.o: In function`usb_recv':
/home/carlos/Desktop/VFS301/cli/cli.c:161: undefined reference to `libusb_bulk_transfer'
/tmp/cchqESW9.o: In function`usb_send':
/home/carlos/Desktop/VFS301/cli/cli.c:180: undefined reference to `libusb_bulk_transfer'
collect2: ld returned 1 exit status
make: **\* [cli] Error 1
I have installed the packages libusb1-0, libusb1-0 dev, make and g++. It supposed to compile it without problem. Do you have any suggestion about this?
I am using Ubuntu 11.10 64bit. Another user claimed as well that cannot compile it and is using 64bit. Do you think is problem with the architecture?
Thanks

**Comment by andree182** [comment]
Hi there,

I am using 11.04, x64 as well and it works - so it cannot be an architecture problem... :-)

You most probably just need more/other libusb packages.. For example the command `pkg-config --libs libusb-1.0` should print something like "-lusb-1.0" - does it? It most likely doesn't...

I guess you need libusb-1.0-0-dev and libusb-1.0-0 (the libusb1-0 you have could be the old version). 

Hope it helps...

**Comment by mog422** [comment]
You must chagne makefile
    gcc -ggdb `pkg-config --cflags libusb-1.0` `pkg-config --libs libusb-1.0` -o $@ proto.c cli.c
->
    gcc -ggdb `pkg-config --cflags libusb-1.0` -o $@ proto.c cli.c `pkg-config --libs libusb-1.0`

**Comment by andree182** [comment]
that sounds reasonable, fixed it in the makefile...

**Comment by vedovatti** [comment]
Amazing! it works!!!!! Thank you!!
